library(data.table)
dat <- fread(input = "household_power_consumption.txt", na.strings="?")
select_dat <- subset(dat,dat$Date == "1/2/2007"|dat$Date == "2/2/2007")
select_dat$datetime <-as.POSIXct(paste(select_dat$Date,select_dat$Time), format = "%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(select_dat$datetime,select_dat$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(select_dat$datetime,select_dat$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(select_dat$datetime,select_dat$Sub_metering_1,type="l",xlab="",ylab="Energy Sub meter")
lines(select_dat$datetime,select_dat$Sub_metering_2,col="red")
lines(select_dat$datetime,select_dat$Sub_metering_3,col="blue")
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(select_dat$datetime,select_dat$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()
